### ISSUE TITLE
Change color on compose button - EMail Module

### ISSUE THREAD

**Issue by christianstayton** [dekamco/cms#14]
In the EMail Module, the COMPOSE button needs be changed to: 4c7dbf

See example: https://tinyurl.com/yxt9ekwg

**Comment by christianstayton** [comment]
Changed the color on button code in CSS but still is not reverting to the new color. 

Maybe CSS in a different folder?

**Comment by christianstayton** [comment]
Fixed

**Comment by Sagar158** [comment]
fixedd
